# Generated by Django 4.2.3 on 2023-08-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='text',
        ),
    ]
