# Generated by Django 4.2.3 on 2023-08-14 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0009_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_at',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 14, 11, 12, 58, 928227, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
