# Generated by Django 4.2.3 on 2023-08-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0010_remove_post_create_at_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
