# Generated by Django 4.2.3 on 2023-08-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0012_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click here to raed blog', max_length=200),
        ),
    ]
