# Generated by Django 4.2.3 on 2023-08-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0013_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
