# Generated by Django 4.2.3 on 2023-08-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0016_usrpfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrpfp',
            name='github_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usrpfp',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='usrpfp',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usrpfp',
            name='website_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
