# Generated by Django 4.2.3 on 2023-09-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0021_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
